// music research
// https://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies
// format https://github.com/keithclark/ZzFXM/tree/master
const JSONMidi = [
  { deltaTime: 0, type: "meta", subtype: "trackName", text: "" },
  {
    deltaTime: 0,
    type: "meta",
    subtype: "timeSignature",
    numerator: 4,
    denominator: 4,
    metronome: 36,
    thirtyseconds: 8,
  },
  {
    deltaTime: 0,
    type: "meta",
    subtype: "timeSignature",
    numerator: 4,
    denominator: 4,
    metronome: 36,
    thirtyseconds: 8,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 192,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 192,
    channel: 0,
    type: "channel",
    noteNumber: 41,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 128,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 41,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 45,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 45,
    velocity: 64,
  },
  {
    deltaTime: 192,
    channel: 0,
    type: "channel",
    noteNumber: 29,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 160,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 29,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 29,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 29,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 33,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 29,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 33,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 29,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 33,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 33,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 35,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 35,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 192,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 41,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 41,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 41,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 41,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 45,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 45,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 41,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 95,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 41,
    velocity: 64,
  },
  {
    deltaTime: 1,
    channel: 0,
    type: "channel",
    noteNumber: 38,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 38,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 38,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 35,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 38,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 35,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 288,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 40,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 40,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 40,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 29,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 40,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 29,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 33,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 33,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 38,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 38,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 41,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 33,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 41,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 33,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 40,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 40,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 35,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 35,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 35,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 35,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 40,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 40,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 43,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 40,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 43,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 40,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 33,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 29,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 33,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 29,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 33,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 33,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 40,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 40,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 33,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 29,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 33,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 29,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 32,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 32,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 31,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 31,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 64,
    channel: 0,
    type: "channel",
    noteNumber: 35,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  {
    deltaTime: 32,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 35,
    velocity: 64,
  },
  {
    deltaTime: 0,
    channel: 0,
    type: "channel",
    noteNumber: 36,
    velocity: 100,
    subtype: "noteOn",
  },
  {
    deltaTime: 96,
    channel: 0,
    type: "channel",
    subtype: "noteOff",
    noteNumber: 36,
    velocity: 64,
  },
  { deltaTime: 0, type: "meta", subtype: "endOfTrack" },
];

// Target format
// The note value describes both the period and attenuation of a note. The period is the integer part of the number and the attentuation is the decimal part (0 - 0.99).

// If the period is a value between 1 and 36 the corresponding note will be played using the channel instrument. When a new period is set any note currently playing in the channel is stopped and the channel attenuation is reset. A note value of 0 indicates a noop and -1 indicates note release (stops playing the note)
const midiNoteTozzfxNote = (midiNote) => {
  const note = midiNote - 23;
  return note;
};

const convert = (midiJson) => {
  // get only noteOn and noteOff events
  const notes = midiJson.filter(
    (event) => event.subtype === "noteOn" || event.subtype === "noteOff"
  );

  const restul = [];
  let lastSubtype;

  for (const note of notes) {
    const { deltaTime, subtype, noteNumber } = note;

    if (deltaTime > 0 && deltaTime % 32 === 0) {
      restul.push(...Array(deltaTime / 32).fill(0));
    }

    if (subtype === "noteOn") {
      restul.push(midiNoteTozzfxNote(noteNumber));
    }
  }
  // split into 64 length arrays
  const result2 = [];
  while (restul.length) {
    result2.push([0, 0, ...restul.splice(0, 64)]);
  }
};

convert(JSONMidi);
